#:kivy 2.3.0
<Sliders@BoxLayout>:
    Label:
        text: str(root.val)


<CheatSheet>:
    orientation: 'vertical'
    padding: '5sp'

    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: str(root.roll)
        Label:
            text: str(root.num_dice)
        Label:
            text: str(root.field)
        Label:
            text: str(root.dst)
        Label:
            text: 'Play' if root.play else 'Stop'

    RollArea:
        id: roll_area

    FieldArea:
        id: field_area

    # OutputArea:

    BoxLayout:
        orientation: 'horizontal'

        Label:
            text: f"Current score:\n{root.stop_value:.1f}"

        Label:
            text: f"Expected score:\n{root.play_value:.1f}"



    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Clear'
            on_press: root.on_clear()
        Button:
            text: 'Solve'
            on_press: root.on_solve()
        Button:
            text: 'Accept'
            on_press: root.on_accept()

<Debug@BoxLayout>:


<RollArea@BoxLayout>:
    orientation: 'vertical'
    Label:
        text: 'Roll Area'
    Sliders:
        id: s0
        key: 0
        target: root.parent.roll
        _root: root.parent
        num_buttons: 8
    Sliders:
        id: s1
        key: 1
        target: root.parent.roll
        _root: root.parent
        num_buttons: 8

    BoxLayout:
        orientation: 'horizontal'
        Button:
            id: s2
            text: 'x3'
            on_press:
                root.on_multiplier(self, root.parent.roll, 2) #int(self.state == 'down')
        Button:
            id: s3
            text: 'x4'
            on_press:
                root.on_multiplier(self, root.parent.roll, 3)
        Button:
            id: s4
            text: 'x5'
            on_press:
                root.on_multiplier(self, root.parent.roll, 4)

    
<FieldArea@BoxLayout>:
    orientation: 'vertical'
    Label:
        text: 'Field Area'

    TextInput:
        id: s0
        multiline: False
        input_filter: 'int'  # Accept only integer characters
        text: str(root.parent.field[0])
        on_text_validate:
            root.parent.field[0] = int(self.text or 0)

    Sliders:
        id: s1
        key: 1
        target: root.parent.field
        _root: root.parent
        num_buttons: 8
    Sliders:
        id: s2
        key: 2
        target: root.parent.field
        _root: root.parent
        num_buttons: 8
    Sliders:
        id: s3
        key: 3
        target: root.parent.field
        _root: root.parent
        num_buttons: 5
        button_labels: ['x1', 'x2', 'x3', 'x4', 'x5']

<OutputArea@BoxLayout>:


# <ActionsArea@BoxLayout>:
#     orientation: 'horizontal'
#     Button:
#         text: 'Solve'
#         on_press: root.on_solve()
#     Button:
#         text: 'Accept'
#         on_press: root.on_accept()