#:kivy 2.3.0
<SliderButton>:
    size_hint_x: None
    width: dp(app.slider_button_width)

    size_hint_y: None
    height: dp(app.slider_button_width)

<CheatSheet>:
    orientation: 'vertical'
    spacing: dp(4)

    BoxLayout:
        size_hint_y: 0.3
        orientation: 'horizontal'

        Label:
            text: f"Current score:\n{root.stop_value:.1f}"

        Label:
            text: f"Expected score:\n{root.play_value:.1f}"

    # # Debug
    # BoxLayout:
    #     orientation: 'horizontal'
    #     size_hint_y: 0.5
    #     Label:
    #         text: str(root.roll)
    #     Label:
    #         text: str(root.num_dice)
    #     Label:
    #         text: str(root.field)
    #     Label:
    #         text: str(root.dst)

    RollArea:
        id: roll_area

    FieldArea:
        id: field_area
    # Output
    BoxLayout:
        size_hint_y: 0.3

        orientation: 'vertical'
        Label:
            text: 'Play' if root.play else 'Stop'
            font_size: '25sp'
            color: (0, 1, 0, 1) if root.play else (1, 0, 0, 1)


    # Buttons
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.3

        Button:
            text: 'Clear'
            on_press: root.on_clear()
        # Button:
        #     text: 'Solve'
        #     on_press: root.on_solve()
        Button:
            text: 'Accept'
            on_press: root.on_accept()

<RollArea@AnchorLayout>:

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: None
        width: dp(8*app.slider_button_width)

        size_hint_y: None
        height: dp(4*app.slider_button_width)

        Label:
            text: 'Roll Area'
        Sliders:
            id: s0
            key: 0
            target: root.parent.roll
            _root: root.parent
            num_buttons: 8
            button_labels: ['1', '1', '2', '3', '4', '5', '6', '7']
        Sliders:
            id: s1
            key: 1
            target: root.parent.roll
            _root: root.parent
            num_buttons: 8
            button_labels: ['2', '1', '2', '3', '4', '5', '6', '7']

        Sliders:
            id: s2
            key: 2
            target: root.parent.roll
            _root: root.parent
            num_buttons: 4
            button_labels: ['x', 'x3', 'x4', 'x5']

    
<FieldArea@AnchorLayout>:
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: None
        width: dp(8*app.slider_button_width)

        size_hint_y: None
        height: dp(5*app.slider_button_width)

        Label:
            text: 'Field Area'

        BoxLayout:
            orientation: 'horizontal'

            Label:
                size_hint_x: None
                width: dp(app.slider_button_width)
                text: '+'

            TextInput:
                id: s0
                multiline: False
                input_filter: 'int'  # Accept only integer characters
                text: str(root.parent.field[0])

                halign: 'center'
                valign: 'middle'  # Optional – for clarity, but not directly respected
                padding: [0, (self.height - self.line_height) / 2]  # vertical centering

                on_text_validate:
                    root.parent.field[0] = int(self.text or 0)

        Sliders:
            id: s1
            key: 1
            target: root.parent.field
            _root: root.parent
            num_buttons: 8
            button_labels: ['1', '1', '2', '3', '4', '5', '6', '7']
        Sliders:
            id: s2
            key: 2
            target: root.parent.field
            _root: root.parent
            num_buttons: 8
            button_labels: ['2', '1', '2', '3', '4', '5', '6', '7']
        Sliders:
            id: s3
            key: 3
            target: root.parent.field
            _root: root.parent
            num_buttons: 5
            button_labels: ['x', 'x2', 'x3', 'x4', 'x5']

<OutputArea@BoxLayout>:

