# Tested: 2024/08/05
# by Kasper Arfman
name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #N.B. Openjdk comes pre-installed, so it is left out here
      # Libt5 removed
      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake

          # Fix error: possibly undefined macro: LT_SYS_SYMBOL_USCORE
          sudo apt-get install libltdl-dev

          pip install --user virtualenv Cython==0.29.33  # Don't use latest Cython
          pip install --user --upgrade buildozer

      # Check if buildozer still requires openjdk version 17.
      # https://buildozer.readthedocs.io/en/latest/installation.html
      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

          # Verify Java
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version
          javac -version
          ls /usr/lib/jvm
          printenv | grep JAVA_HOME


          yes | buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk